

batch_file <- function(fcurrun,
                       gamsexe,
                       work_dir,
                       dat_dir
                       ){
  
  fle2wrt <- file(fcurrun, open = "wt")

  cat("********************************************************************",
      "\n*",
      "\n  * Batch file for production runs of agclim50 project",
      "\n* Also a log for settings that are hardecoded somewhere and not visible in GUI settings",
      "\n*",
      "\n  * Author: P Witzke, ...",
      "\n*",
      "\n  ********************************************************************", file = fle2wrt)
  
  cat("\n  ontext",
      "\n", paste0("  gamsexe = ", gamsexe), 
      "\n", paste0("  work dir = ", work_dir),
      "\n", paste0("  dat dir    = ", dat_dir),
      "\n",
      "\n  output dir = D:\\dev\\CAPRImodel\\epnf\\output\\batchOutput_x",
      "\n  res dir    = D:\\dev\\CAPRImodel\\epnf\\output\\results",
      "\n  restartdir = D:\\dev\\CAPRImodel\\epnf\\output\\restart",
      "\n  * If you are NOT working on a network drive the following is ok:",
      "\n    *  scr dir    = ..\\output\\temp",
      "\n  * When the current directory is on a network drive it is necessary to set the scratch directory to a directory on your hard disc:",
      "\n  scr dir    = D:\\dev\\CAPRImodel\\epnf\\output\\temp",
      "\n  number of processors = 32",
      "\n  gams options =   pw=200 errmsg=1 gdxcompress=1 ps=0",
      "\nofftext", file = fle2wrt)
  
  cat("\n* Adrian server",
      "\n*  gamsexe =   C:\\Apps\\GAMS\\win64\\25.1\\gams.exe",
      "\n*  scr dir    = d:\\dev\\CAPRImodel\\temp\\",
      "\n*  res dir    = d:\\dev\\CAPRImodel\\capriresults_ecampa3",
      "\n*  number of processors = 28",
      "\n*  output dir = ..\\output\\batchOutput",
      "\n  output dir = d:\\dev\\CAPRImodel\\epnf\\output\\batchOutput_x", file = fle2wrt)
  
  cat("\n*  MACRO = newresultsout ..\\..\\leipadr\\results",
      "\n*  MACRO = newresultsout ..\\..\\users\\leipadr\\results",
      "\n  MACRO = newresultsout d:\\dev\\CAPRImodel\\users\\rotllxa\\results", file = fle2wrt)
  
  cat("\n* -------------------------------------------",
      "\n* Declare MACRO strings to use in this batch",
      "\n* -------------------------------------------", file = fle2wrt)
  
  cat("\nMACRO = eu27Countries BL000000\\SE000000\\DK000000\\DE000000\\EL000000\\ES000000\\FR000000\\IR000000\\IT000000\\NL000000\\AT000000\\PT000000\\FI000000\\UK000000\\CY000000\\EE000000\\LV000000\\LT000000\\MT000000\\PL000000\\SK000000\\BG000000\\CZ000000\\HU000000\\SI000000\\RO000000",
      "\n  MACRO = candidateCountries CS000000\\AL000000\\MO000000\\HR000000\\BA000000\\MK000000\\KO000000\\TUR",
      "\n  MACRO = otherCountries NO000000",
      "\n  MACRO = allCountries %eu27Countries%\\%otherCountries%\\%candidateCountries%",
      "\n  *  MACRO = calibrationYears 2030\\2050",
      "\n  MACRO = calibrationYears 2030",
      "\n  MACRO = allCountriesOrdered NO000000\\TUR\\UK000000\\BL000000\\DK000000\\DE000000\\EL000000\\ES000000\\FR000000\\IR000000\\IT000000\\NL000000\\AT000000\\PT000000\\SE000000\\FI000000\\CY000000\\CZ000000\\EE000000\\HU000000\\LT000000\\LV000000\\MT000000\\PL000000\\SI000000\\SK000000\\RO000000\\BG000000\\AL000000\\MK000000\\CS000000\\MO000000\\HR000000\\BA000000\\KO000000",
      "\n  MACRO = bas 08",
      "\n  MACRO = baseyear 20%bas%",
      "\n  MACRO = refScenario mtr_rd_ref",
      "\n  MACRO = calScenario mtr_rd_cal",
        
      "\n  MACRO = allCountriesComma BL000000 \"Belgium and Luxembourg\",DK000000 \"Denmark\",DE000000 \"Germany\",EL000000 \"Greece\",ES000000 \"Spain\",FR000000 \"France\",IR000000 \"Irland\",IT000000 \"Italy\",NL000000 \"The Netherlands\",AT000000 \"Austria\",PT000000 \"Portugal\",SE000000 \"Sweden\",FI000000 \"Finland\",UK000000 \"United Kingdom\",CZ000000 \"Czech Republic\",HU000000 \"Hungary\",PL000000 \"Poland\",SI000000 \"Slovenia\",SK000000 \"Slovak Republic\",EE000000 \"Estonia\",LT000000 \"Lithuania\",LV000000 \"Latvia\",CY000000 \"Cyprus\",MT000000 \"Malta\",BG000000 \"Bulgaria\",RO000000 \"Romania\",NO000000 \"Norway\",TUR \"Turkey\",AL000000 \"Albania\",MK000000 \"Macedonia\",CS000000 \"Serbia\",MO000000 \"Montenegro\",HR000000 \"Croatia\",BA000000 \"Bosnia and Herzegovina\",KO000000 \"Kosovo\"",
        
        
      "\n  * select one of the following aglink projection",
      "\n  MACRO = AglinkVersion Aglink2017OECD",
      "\n  *  MACRO = AglinkVersion Aglink2014DgAgri",
        
      "\n  * decide whether UK should be part of the EU, brexit scenarios are only operational when UK_in_EU is OFF",
      "\n  * Note: THe switch is not yet synchronised into Ecampa3 branch => Need to use the older global variable 'EU28 = ON'",
      "\n  * MACRO = UK_in_EU OFF",
      "\n  MACRO = UK_in_EU ON",
        
      "\n  MACRO = Run_scenario_without_market_model     Off",
      "\n  MACRO = Run_scenario_with_market_model        On", file = fle2wrt)
  
  
  cat("\nIF %Run_scenario_without_market_model% = ON",
      "\n* -------------------------------------------",
      "\n*   ",
      "\n*  CAPMOD: Calibration of mitigation measures and test of calibration",
      "\n*          => Produces results\\envind\\costsavings_ini_20830.gdx with v_miti.m",
      "\n*             These marginal values are used in a kind of pmp approach to specify the unobserved costs",
      "\n*             for those options that interact in complicated ways with other parts of the supply model:",
      "\n*             lowNFeed, feed additives, breeding options, histosol protection",
      "\n*  ",
      "\n* -------------------------------------------",
      
      "\n*   ",
      "\n  task = Run scenario without market model",
         
      "\n  EU28 = %UK_in_EU%",
         
      "\n  Generate GAMS child processes on different threads = OFF",
      "\n  Generate CMD per Thread = OFF",
      "\n  GHG abatement technology = endog",
      "\n  Base year = %baseyear%",
      "\n  Countries = BL000000 \"Belgium and Luxembourg\",DK000000 \"Denmark\",DE000000 \"Germany\",EL000000 \"Greece\",ES000000 \"Spain\",FR000000 \"France\",IR000000 \"Irland\",IT000000 \"Italy\",NL000000 \"The Netherlands\",AT000000 \"Austria\",PT000000 \"Portugal\",SE000000 \"Sweden\",FI000000 \"Finland\",UK000000 \"United Kingdom\",CZ000000 \"Czech Republic\",HU000000 \"Hungary\",PL000000 \"Poland\",SI000000 \"Slovenia\",SK000000 \"Slovak Republic\",EE000000 \"Estonia\",LT000000 \"Lithuania\",LV000000 \"Latvia\",CY000000 \"Cyprus\",MT000000 \"Malta\",BG000000 \"Bulgaria\",RO000000 \"Romania\",NO000000 \"Norway\",TUR \"Turkey\",AL000000 \"Albania\",MK000000 \"Macedonia\",CS000000 \"Serbia\",MO000000 \"Montenegro\",HR000000 \"Croatia\",BA000000 \"Bosnia and Herzegovina\",KO000000 \"Kosovo\"",
      "\n  Regional breakdown = NUTS2",
      "\n  Non-default FAO trade matrix vintage = OFF",
      "\n  FAO trade matrix vintage (determines FAOregions) = FAO_trade_matrix_1986_2013",
      "\n  Number of iterations = 1",
      "\n  Aggregates for activities and commodities = ON",
      "\n  Environmental Indicators = ON",
      "\n  Life-cycle assessment for energy = OFF",
      "\n  Multi-functionality indicators = ON",
      "\n  Iteration tracking = ON",
      "\n  Sensitivity experiments with features in supply model = OFF",
      "\n  Load meta information from older task = ON",
      "\n  Additional input data identifier = ",
      "\n  Additional result type identifier = ", 
      "\n  Override results_in: = ",
      "\n  Override results_out: = ",
      "\n  Override restart_in: = ",
      "\n  Override restart_out: = ",
      "\n  Solution printing = Suppress",
      "\n  *Solution printing = Variables and equations",
      "\n  Print gams code to listing = onListing",
      "\n  Solprint = On",
      "\n  Limrow = 0.0",
      "\n  Limcol = 0.0",
      
      "\n\nSimulation years = 2030",
      "\n  Non-default reference scenario for carbon accounting = On",
      "\n  Reference scenario for carbon accounting = res_2_0810mtr_rd_ref",
      "\n\n",
      
      "\n*ontext",
      "\n* refpol_endotech_all_ini = calibration scenario to get marginal values for initial implementaiton shares",
      "\n  Scenario description = ecampa3\\refpol_endotech_all_ini",
      "\n  execute=Gamsrun",
      
      "\n\n* refpol_endotech_all_ini = calibration scenario to get marginal values for max implementaiton shares",
      "\n  Scenario description = ecampa3\\refpol_endotech_all_max",
      "\n  execute=Gamsrun",
      
      "\n\n* refpol_endotech_all_noc = test scenario with all mitigation deactivated (incl from reference)",
      "\n  Scenario description = ecampa3\\refpol_endotech_noc_sup",
      "\n  execute=Gamsrun",
      "\n",
      "\n* test scenario to check calibration for initial implementation shares (subsidies = 0, reference)",
      "\n  Scenario description = ecampa3\\refpol_endotech_all_sup",
      "\n  execute=Gamsrun",
      "\n*offtext",
      "\n* -------------------------------------------",
      "\n  * ",
      "\n  *  CAPMOD: test scenarios to check calibration  (also only with supply models)",
      "\n  * ",
      "\n  * ------------------------------------------",
      "\n  ",
      "\n  offtext",
      "\n  ENDIF",
      "\n",
      "\nIF %Run_scenario_with_market_model% = ON",
      "\n* -------------------------------------------",
      "\n  *",
      "\n  task = Run scenario with market model",
      "\n*  CAPMOD: test scenarios to check effect of 100 Euro co2 tax with single (or small group) measures active only",
      "\n*",
      "\n  * -------------------------------------------",
      "\n  *",
      "\n  EU28 = %UK_in_EU%",
      "\n  Scenario description = epnf\\epnf_scenarios",
      "\n  Scenario description CGE = cge_rd_noChg",
      "\n  Generate GAMS child processes on different threads = OFF",
      "\n  Generate CMD per Thread = OFF",
      "\n  GHG abatement technology = endog",
      "\n  Base year = %baseyear%",
      "\n    Countries = %allCountriesComma%",
      "\n    Regional breakdown = NUTS2",
      "\n  Non-default reference scenario for carbon accounting = OFF",
      "\n  Non-default FAO trade matrix vintage = OFF",
      "\n  FAO trade matrix vintage (determines FAOregions) = FAO_trade_matrix_1986_2013",
      "\n  ",
      "\n  * ---- Modules and algorithms",
      "\n  Endogenous bio-fuel markets in global market model = ON",
      "\n  Policy blocks (additional geographical layer) = OFF",
      "\n  Endogenous margins between trade block and country prices = OFF",
      "\n  Advanced tariff aggregation module = OFF",
      "\n  Endogenous young animal markets = ON",
      "\n  Regional CGEs = OFF",
      "\n  ",
      "\n  Number of iterations = 25",
      "\n  Use lower price iterations weights after iteration = 20",
      "\n  Alternative GAMS license file for GHG emission estimation = gamslice",
      "\n  ",
      "\n  * ---  Reporting",
      "\n  Aggregates for activities and commodities = ON",
      "\n  Environmental Indicators = ON",
      "\n  Life-cycle assessment for energy = OFF",
      "\n  Multi-functionality indicators = OFF",
      "\n  Iteration tracking = ON",
      "\n  Sensitivity experiments with features in supply model = OFF",
      "\n  ",
      "\n  * --- Methodological switches CGE (only active if Region CGEs == ON)",
      "\n  Endogenous net migration = ON",
      "\n  Fixed budget for factor subsidies = ON",
      "\n  Capital stock = DPSV rule",
      "\n  Labor supply = Wage curve",
      "\n  Capital mobility = Sluggish",
      "\n  Labor mobility = Sluggish",
      "\n  Land mobility = Sluggish",
      "\n  Closure current account and trade balance = Exchange rate",
      "\n  Closure household account = Spending",
      "\n  Closure government account = Spending",
      "\n  ",
      "\n  * --- Debug options",
      "\n  Load meta information from older task = ON",
      "\n  Override results_in: =",
      "\n  Override results_out: = %newresultsout%",
      "\n  Override restart_in: =",
      "\n  Override restart_out: =",
      "\n  ",
      "\n  *  --- Debug options: Supply model",
      "\n  Solution printing = Suppress",
      "\n  Determine point price elasticities = OFF",
      "\n  Print gams code to listing = onListing",
      "\n  Solprint = Off",
      "\n  Limrow = 0.0",
      "\n  Limcol = 0.0",
      "\n  *  --- Debug options: Market model",
      "\n  Maximum number of pre-steps market model = 15",
      "\n  Solution print at preparatory solve = OFF",
      "\n  Abort after preparatory solve = OFF",
      "\n  Solution print for pre-steps in 1st iteration with abort = OFF",
      "\n  Plus iterlim to zero for 1st pre-steps in 1st iteration = OFF",
      "\n  Number of presteps before abort = 1",
      "\n  Kill simini file = Off",
      "\n",
      "\n* --- SSP Options",
      "\n  Select SSP Options = On",
      "\n  SSP decomposition analysis = OFF",
      "\n  Macro data = SSP2mp",
      "\n  Reference SSP = SSP2mp",
      "\n  gdpSSP = OFF",
      "\n  Taste shifter = MAgPIE",
      "\n  Diet data = SSP2mp",
      "\n  Dietshock = PercentageChange",
      "\n  PIK Climate Change scenario = ''",
      "\n  CPrice = 0",
      "\n  Policy Type = refpol",
      "\n",
      "\n  Simulation years = 2030,",
      "\n*  execute=gamsrun",
      "\n", file = fle2wrt)
  
  cat("\n  Number of iterations = 3",
      "\n  startParallel",
      "\n*    FOR runSSPs = SSP1\\SSP2\\SSP3\\SSP4\\SSP5",
      "\n*    Macro data = %runSSPs%mp",
      "\n                        FOR runCPrice = 1\\10\\50\\100",
      "\n                                CPrice = %runCPrice%",
      "\n        execute=gamsrun",
      "\n                        ENDFOR",
      "\n*               ELSE",
      "\n*                       execute=gamsrun",
      "\n*               ENDIF",
      "\n*    ENDFOR",
      "\n  collectParallel",
      "\n\n", file = fle2wrt)
  
  cat("\n* If 2010 has not been deactivated, you may set 'Non-default reference scenario... on' and 'Reference scenario... = res_2_%bas%14mtr_rd_ref'",
      "\n  Non-default reference scenario for carbon accounting = On",
      "\n  Reference scenario for carbon accounting = res_2_%bas%10mtr_rd_ref",
      "\n*execute=gamsrun",
      "\n",
      "\n",
      "\nontext",
      "\n",
      "\n* Starting point of 2030 MACC with carbon price = 0 would be reference for total effect (not used, with market model)",
      "\n* This is also reference point for co2tax100_endotech_ref",
      "\n  Scenario description = ecampa3\\refpol_endotech_all",
      "\n*  execute=gamsrun",
      "\n",
      "\n* test scenarios to check calibration for max implementation shares (subsidies that should give _max scenario): not used in D3",
      "\n  Scenario description = epnf\\epnf_scenarios",
      "\n  execute=Gamsrun",
      "\nofftext",
      "\nontext",
      "\n* Endpoint of 2030 MACC with carbon price = 100 would give total effect  (not used, with market model)",
      "\n  Scenario description = ecampa3\\co2tax100_endotech_all",
      "\n  execute=Gamsrun",
      "\n",
      "\n* For Table 10+11+12+13:",
      "\n  * reference for check of technological options must be a scenario with tech options as in the reference run:",
      "\n  Scenario description = ecampa3\\co2tax100_endotech_ref",
      "\n  execute=Gamsrun",
      "\n",
      "\n* For Table 14/15:",
      "\n  Scenario description = ecampa3\\co2tax100_endotech_pf",
      "\n  execute=Gamsrun",
      "\n",
      "\n* For Table 14/15:",
      "\n  Scenario description = ecampa3\\co2tax100_endotech_ferttime",
      "\n  execute=Gamsrun",
      "\n",
      "\n* For Table 14/15:",
      "\n  Scenario description = ecampa3\\co2tax100_endotech_vrt",
      "\n  execute=Gamsrun",
      "\n",
      "\n* For Table 14/15:",
      "\n  Scenario description = ecampa3\\co2tax100_endotech_nitrinh",
      "\n  execute=Gamsrun",
      "\n",
      "\n* For Table 14/15:",
      "\n  Scenario description = ecampa3\\co2tax100_endotech_wintercov",
      "\n  execute=Gamsrun",
      "\n",
      "\n* For Table 14/15:",
      "\n  Scenario description = ecampa3\\co2tax100_endotech_histo",
      "\n  execute=Gamsrun",
      "\n",
      "\n* For Table 14/15:",
      "\n  Scenario description = ecampa3\\co2tax100_endotech_rice",
      "\n  execute=Gamsrun",
      "\n",
      "\n* For Table 14/15:",
      "\n  Scenario description = ecampa3\\co2tax100_endotech_legsh",
      "\n  execute=Gamsrun",
      "\n",
      "\n* For Tables 16+18:",
      "\n  Scenario description = ecampa3\\co2tax100_endotech_ammo",
      "\n  execute=Gamsrun",
      "\n",
      "\n* For Tables 16+17:",
      "\n  Scenario description = ecampa3\\co2tax100_endotech_myld",
      "\n  execute=Gamsrun",
      "\n",
      "\n* For Table 16+17:",
      "\n  Scenario description = ecampa3\\co2tax100_endotech_feff",
      "\n  execute=Gamsrun",
      "\n",
      "\n* For Table 16+17:",
      "\n  Scenario description = ecampa3\\co2tax100_endotech_lnf",
      "\n  execute=Gamsrun",
      "\n",
      "\n* For Table 16+17:",
      "\n  Scenario description = ecampa3\\co2tax100_endotech_line",
      "\n  execute=Gamsrun",
      "\n",
      "\n* For Table 16+17:",
      "\n  Scenario description = ecampa3\\co2tax100_endotech_nitr",
      "\n  execute=Gamsrun",
      "\n",
      "\n* For Table 16+17:",
      "\n  Scenario description = ecampa3\\co2tax100_endotech_vac",
      "\n  execute=Gamsrun",
      "\n",
      "\n* For Table 16+17:",
      "\n  Scenario description = ecampa3\\co2tax100_endotech_ad",
      "\n  execute=Gamsrun",
      "\n",
      "\n* For Tables 22-25:",
      "\n  Scenario description = ecampa3\\refpol_endotech_icowfx",
      "\n  execute=gamsrun",
      "\nofftext",
      "\n",
      "\nENDIF", file = fle2wrt)
  
  
  
  close(fle2wrt)
  
  
}

